### ISSUE TITLE
开启checkpoint后异常

### ISSUE THREAD

**Issue by hehuiyuan** [TopSpoofer/hbrdd#1]
18/08/22 15:50:41 ERROR Utils: Exception encountered
java.io.NotSerializableException: org.apache.hadoop.conf.Configuration
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)

我这是spark streaming任务

stream.foreach{rdd=>rdd.put2hase(....)}
应该是put2hbase方法中：def put2Hbase(tableName: String)(implicit config: HbRddConfig)

调用了config.getHbaseConfig

然后这个方法实现是：def getHbaseConfig = HBaseConfiguration.create(config)

create方法中创建了Configuration conf = new Configuration();　　不能序列化，因为这个类没有实现序列化

但是我不知道为什么会报错，不开启checkpoint没事，开启了报错

**Comment by hehuiyuan** [comment]
解决办法：
object HbRddConfig {
  type configOption = (String, String)
  private[HbRddConfig] case class HbaseOption(name: String, value: String)

  def apply(config: Configuration): HbRddConfig = new HbRddConfig(config)

  def apply(configs: configOption*): HbRddConfig = {
    **val hbConfig = HBaseConfiguration.create()**

    for {
      option <- configs
      hbOption = HbaseOption(option._1, option._2) //使用新的case class 只是为了表达更加清晰
    } hbConfig.set(hbOption.name, hbOption.value)

    this.apply(hbConfig)
  }

**Comment by naudachu** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!
FireAny, @zyxzyxzyx, @RyanBasics, @289699522, @heygum, @goodjob0823, @jinbiaochenstayhungry, @maoruibin, @flykingmz, @onemedicine, @Gah0, @wafeishushu, @ConnorChen97, @ylwzld, @heyehang, @zhangsubiin, @Wangjiaji007, @kojie2008, @Jatom-c, @qiwaa, @hy04, @mt995, @dql529, @xusai2014, @XIXUANHAO, @Sillysillysilly, @hyper0x, @ycxw320, @kaioujiang, @lazyparser, @BaofengWu, @windyqingyun, @Hugh-Zhu, @kenshou, @wpp2014, @ZEALi, @odboy, @waterliu99, @GuBYg, @wuMaoTou, @objnf-dev, @liuhao2018, @Caomeiniunai, @Lincest, @liuxing19760828, @qdpoboy, @yhsy, @lijinsheng, @Hodgewhj, @cdf1999

**Comment by Jatom-c** [comment]
你好，我已经收到你的邮件了。       --蔡佳桐
